### ISSUE TITLE
No guide on how to download and compatible code for this for the macOS

### ISSUE THREAD

**Issue by ghost** [random11x/agg23-fpga-gameandwatch-hand-hold-guide#2]
I’m trying to use your code to download MAME Game & Watch games on my Analogue Pocket. I 100% flow your instructions, but it is still not working for me because I only have a MacBook and the code especially the patch.bat is not compatible with it. Can you please make a guide and a version of patch.bat for the macOS.

**Comment by random11x** [comment]
For Mac instructions follow [the directions from](https://github.com/agg23/fpga-gameandwatch/blob/master/docs/rom_generator.md) @agg23. I don't think making a "dummy guide" will help you on a Mac, it wouldn't really be able to make it that much simpler. There are also newer downloaders / pocket updater apps that will run the generator tool for you so you don't need to bother running it yourself, that's probably the recommended solution for Mac or PC going forward.
